services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vlasato23
      MYSQL_USER: vlasato23
      MYSQL_PASSWORD: p6ctWXir
    volumes:
      - db_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  db_data:
